# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kw2yTxywLHkPn5hNd3TKEAfFPxWjd5K-
"""

# ============================================================
#  Colab: immagine -> immagine_test2.h (uint8 grezzo) + test sul modello
#  Esegui tutto in UNA cella. Ti chiede di caricare 2 file:
#    1) la foto (jpg/png)   2) il file .tflite
# ============================================================
!pip install -q ai-edge-litert

import re, io, os
import numpy as np
from PIL import Image, ImageOps
from google.colab import files
from ai_edge_litert.interpreter import Interpreter

# ---------------- CONFIGURAZIONE ----------------
SIZE = 128
HEADER_NAME = "immagine_test2.h"     # deve coincidere con l'#include nel .c
# ------------------------------------------------

NAMES = ["apple_pie","baby_back_ribs","baklava","beef_carpaccio","beef_tartare",
"beet_salad","beignets","bibimbap","bread_pudding","breakfast_burrito","bruschetta",
"caesar_salad","cannoli","caprese_salad","carrot_cake","ceviche","cheese_plate",
"cheesecake","chicken_curry","chicken_quesadilla","chicken_wings","chocolate_cake",
"chocolate_mousse","churros","clam_chowder","club_sandwich","crab_cakes",
"creme_brulee","croque_madame","cup_cakes","deviled_eggs","donuts","dumplings",
"edamame","eggs_benedict","escargots","falafel","filet_mignon","fish_and_chips",
"foie_gras","french_fries","french_onion_soup","french_toast","fried_calamari",
"fried_rice","frozen_yogurt","garlic_bread","gnocchi","greek_salad",
"grilled_cheese_sandwich","grilled_salmon","guacamole","gyoza","hamburger",
"hot_and_sour_soup","hot_dog","huevos_rancheros","hummus","ice_cream","lasagna",
"lobster_bisque","lobster_roll_sandwich","macaroni_and_cheese","macarons",
"miso_soup","mussels","nachos","omelette","onion_rings","oysters","pad_thai",
"paella","pancakes","panna_cotta","peking_duck","pho","pizza","pork_chop",
"poutine","prime_rib","pulled_pork_sandwich","ramen","ravioli","red_velvet_cake",
"risotto","samosa","sashimi","scallops","seaweed_salad","shrimp_and_grits",
"spaghetti_bolognese","spaghetti_carbonara","spring_rolls","steak",
"strawberry_shortcake","sushi","tacos","takoyaki","tiramisu","tuna_tartare","waffles"]
assert len(NAMES) == 101 and NAMES[76] == "pizza"

# ---------- 1) Upload dei file ----------
print("Carica la FOTO e il file .tflite (puoi selezionarli insieme)")
up = files.upload()

img_files = [n for n in up if n.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.bmp'))]
if not img_files:
    raise FileNotFoundError("Nessun file immagine (jpg, jpeg, png, webp, bmp) è stato caricato.")
img_name = img_files[0]

tfl_files = [n for n in up if n.lower().endswith('.tflite')]
if not tfl_files:
    raise FileNotFoundError("Nessun file .tflite è stato caricato. Si prega di caricare sia l'immagine che il modello .tflite.")
tfl_name = tfl_files[0]

print("Foto:", img_name, "| Modello:", tfl_name)

# ---------- 2) Preprocessing ----------
def prepara(path, mode="crop", resample=Image.BILINEAR):
    img = Image.open(path)
    img = ImageOps.exif_transpose(img)      # corregge l'orientamento delle foto da telefono
    img = img.convert("RGB")                # forza SEMPRE 3 canali (niente RGBA/grigio)

    if mode == "crop":                      # crop centrale quadrato
        w, h = img.size; s = min(w, h)
        img = img.crop(((w - s)//2, (h - s)//2, (w + s)//2, (h + s)//2))
        img = img.resize((SIZE, SIZE), resample)
    elif mode == "pad":                     # ridimensiona con padding (bande nere) senza deformare
        img.thumbnail((SIZE, SIZE), resample)
        bande = Image.new("RGB", (SIZE, SIZE), (0, 0, 0))
        bande.paste(img, ((SIZE - img.size[0]) // 2, (SIZE - img.size[1]) // 2))
        img = bande
    else:                                   # squash: l'immagine viene deformata dal resize diretto
        img = img.resize((SIZE, SIZE), resample)

    arr = np.array(img, dtype=np.uint8)     # pixel grezzi 0..255, NESSUNA sottrazione
    assert arr.shape == (SIZE, SIZE, 3), arr.shape
    return arr

# ---------- 3) Modello ----------
it = Interpreter(model_path=tfl_name)
it.allocate_tensors()
d_in, d_out = it.get_input_details()[0], it.get_output_details()[0]
print("Input :", d_in["shape"], d_in["dtype"].__name__, "quant (scale, zp) =", d_in["quantization"])
print("Output:", d_out["shape"], d_out["dtype"].__name__)
assert d_in["dtype"] == np.uint8, "Il modello NON prende uint8: cambia il preprocessing!"

def classifica(arr):
    x = arr.reshape(1, SIZE, SIZE, 3).astype(np.uint8)
    it.set_tensor(d_in["index"], x)
    it.invoke()
    p = it.get_tensor(d_out["index"])[0].astype(np.float32)
    top = np.argsort(p)[::-1][:5]
    return [(int(i), NAMES[i], float(p[i])) for i in top]

# ---------- 4) Confronto e ricerca automatica del migliore ----------
varianti = {
    "crop + bilinear": dict(mode="crop", resample=Image.BILINEAR),
    "crop + bicubic" : dict(mode="crop", resample=Image.BICUBIC),
    "crop + nearest" : dict(mode="crop", resample=Image.NEAREST),
    "squash + bilinear": dict(mode="squash", resample=Image.BILINEAR),
    "pad + bilinear"  : dict(mode="pad", resample=Image.BILINEAR),
}

print("\n=== TOP-3 per variante di preprocessing ===")
miglior_p = -1.0
scelta_ottimale = None
nome_variante_migliore = ""

for nome, kw in varianti.items():
    risultati = classifica(prepara(img_name, **kw))
    # Il primo elemento in 'risultati' è il top-1 predetto da questa variante
    top1_classe, top1_nome, top1_prob = risultati[0]

    print(f"{nome:18s}", " | ".join(f"{n} {p*100:5.1f}%" for _, n, p in risultati[:3]))

    # Cerchiamo la variante che ha espresso la massima sicurezza (probabilità più alta sul suo top-1)
    if top1_prob > miglior_p:
        miglior_p = top1_prob
        scelta_ottimale = kw
        nome_variante_migliore = nome

print(f"\n--> Variante selezionata automaticamente per l'export: {nome_variante_migliore} ({miglior_p*100:.1f}%)")

# ---------- 5) Applicazione della variante migliore ----------
arr = prepara(img_name, **scelta_ottimale)
flat = arr.flatten()
assert flat.size == SIZE * SIZE * 3 == 49152

print("\nStatistiche pixel -> min:", flat.min(), " max:", flat.max(),
      " media: %.1f" % flat.mean(), " std: %.1f" % flat.std())
print("Primi 8 valori:", flat[:8].tolist())

# ---------- 6) Scrittura dell'header ----------
with open(HEADER_NAME, "w") as f:
    f.write(f"/* Autogenerato basato su variante ottimale: {nome_variante_migliore} */\n")
    f.write("/* Pixel RGB uint8 grezzi 0..255, layout HWC (128x128x3) */\n")
    f.write("#ifndef IMMAGINE_TEST2_H_\n#define IMMAGINE_TEST2_H_\n\n#include <stdint.h>\n\n")
    f.write(f"const uint8_t immagine_array[{flat.size}] = {{\n")
    for i in range(0, flat.size, 16):
        f.write("    " + ", ".join(str(int(v)) for v in flat[i:i+16]) + ",\n")
    f.write("};\n\n#endif\n")

# ---------- 7) Verifica: rileggo l'header e ripeto la classificazione ----------
txt = open(HEADER_NAME).read().split("{", 1)[1]
riletto = np.array(re.findall(r"\d+", txt), dtype=np.uint8)
assert riletto.size == 49152, riletto.size
assert np.array_equal(riletto, flat), "L'header NON corrisponde all'array!"
r = classifica(riletto.reshape(SIZE, SIZE, 3))
print("\n=== RISULTATO DALL'HEADER APPENA SCRITTO ===")
for i, n, p in r:
    print(f"  {i:3d} {n:24s} {p*100:6.2f} %")

# anteprima di cosa vede davvero la rete
display(Image.fromarray(arr).resize((256, 256), Image.NEAREST))

files.download(HEADER_NAME)
print("\nOK. Copia", HEADER_NAME, "in Core/Inc del progetto CubeIDE, poi Clean + Build.")
print("Nel .c imposta IMAGE_ARRAY_IS_SHIFTED = 0.")